Capstone2019/Models/Composition.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone2019.Models
{
    public class Composition
    {
        [Key]
        public int Composition_ID { get; set; }
        [Required]
        public int Owner_ID { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Tags { get; set; }
        [Required]
        public DateTime Date_Created { get; set; }

        public DateTime Last_Saved { get; set; }
    }
}

Capstone2019/Models/ErrorViewModel.cs
using System;

namespace Capstone2019.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Capstone2019/Models/Favourite.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Capstone2019.Models
{
    public class Favourite
    {
        [Key]
        public int Favourite_ID { get; set; }
        [Required]
        public int Record_ID { get; set; }
        [Required]
        public int Owner_ID { get; set; }
    }
}

Capstone2019/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace Capstone2019.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthenticationSchemeProvider authenticationSchemeProvider;

        public AuthController(IAuthenticationSchemeProvider _authenticationSchemeProvider)
        {
            this.authenticationSchemeProvider = _authenticationSchemeProvider;
        }



        public async Task<IActionResult> Login()
        {
            var allSchemeProvider = (await authenticationSchemeProvider.GetAllSchemesAsync())
                .Select(n => n.DisplayName).Where(n => !String.IsNullOrEmpty(n));

            return View(allSchemeProvider);
        }

        public IActionResult SignIn(String provider)
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, provider);
        }

        public async Task<IActionResult> SignOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index","Home");
        }
    }
}

Capstone2019/Controllers/CompositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Capstone2019.Controllers
{
    public class CompositionsController : Controller
    {
        public IActionResult Compositions()
        {
            ViewData["Message"] = "Your Compositions page.";
            return View();
        }
    }
}

Capstone2019/Controllers/FavouritesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Capstone2019.Controllers
{
    public class FavouritesController : Controller
    {
        public IActionResult Favourites()
        {
            ViewData["Message"] = "Your Favourites page.";

            return View();
        }
    }
}

Capstone2019/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Capstone2019.Models;

namespace Capstone2019.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Capstone2019/Controllers/SongmakerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Capstone2019.Controllers
{
    public class SongmakerController : Controller
    {
        public IActionResult Songmaker()
        {
            return View();
        }
    }
}

Capstone2019/Views/Compositions/Compositions.cshtml
@{
    ViewData["Title"] = "Compositions";
}
@if (User.Identity.IsAuthenticated)
{
    <div>
        <h2 id="tabletitle">Compositions:<img id="edit" onclick="makeEditable()" /></h2>
    </div>
    <div class="input-group">
        <form method="post" action="delete_comp.php">
            <input id="filename" name="filename" type="text" class="form-control" placeholder="File Name">
            <button id="openButton" name="openButton" type="submit" onclick="openFile()" class="btn btn-primary">Open</button>
            <button id="deleteButton" name="deleeteButton" type="submit" onclick="deleteFile()" class="btn btn-primary">Delete</button>
        </form>
    </div>
    <div>
        <table class="table table-striped table-dark">

            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Name</th>
                    <th scope="col">Tags</th>
                    <th scope="col">Date Created</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
}

Capstone2019/Views/Favourites/Favourites.cshtml
@{
    ViewData["Title"] = "Favourites";
}
@if (User.Identity.IsAuthenticated)
{ 
    <div>
        <h2 id="tabletitle">Favourites:<img id="edit" onclick="makeEditable()" /></h2>
    </div>
<div class="input-group">
    <form method="post" action="delete_fav.php">
        <input id="filename" name="filename" type="text" class="form-control" placeholder="File Name" />
        <button id="deleteButton" type="submit" class="btn btn-primary">Remove</button>
    </form>
</div>

<table class="table table-striped table-dark">

    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Tags</th>
            <th scope="col">Date Created</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

}

Capstone2019/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Capstone2019/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Capstone2019</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/customStyle.css" />
    <link rel="stylesheet" href="~/css/songmakerStyle.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Capstone2019</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Compositions" asp-action="Compositions">Compositions</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Favourites" asp-action="Favourites">Favourites</a></li>
                        <li class="nav-item"><a class="nav-link text-dark" asp-area="" asp-controller="Songmaker" asp-action="Songmaker">Songmaker</a></li>
                    </ul>
                    <ul id="SignIn_LogOut" class="navbar-nav">
                        @if (User.Identity.IsAuthenticated)
                        {
                            //controller= profile action == index
                            <li><a class="nav-link text-dark ml-auto" >@User.Identity.Name</a></li>

                            <li><a asp-area="" asp-controller="Auth" class="nav-link text-dark ml-auto" asp-action="SignOut">Sign Out</a></li>
                        }
                        else
                        {
                            <li><a asp-area="" asp-controller="Auth" class="nav-link text-dark ml-auto" asp-action="Login">Log In</a></li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (!User.Identity.IsAuthenticated)
    {
        <h1>You are not logged in</h1>
    }
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Capstone2019 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Capstone2019/Views/Songmaker/Songmaker.cshtml
@{
    ViewData["Title"] = "Songmaker";
}
<audio preload="auto" class="audio"></audio>

<div class="row">
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
    <div id="note_blk" class="col-sm"></div>
</div>